# Generated by Django 5.1 on 2024-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('instrument', models.CharField(choices=[('Guitar', 'Guitar'), ('Piano', 'Piano'), ('Drums', 'Drums'), ('Violin', 'Violin'), ('Flute', 'Flute'), ('Trumpet', 'Trumpet'), ('Ukulele', 'Ukulele')], max_length=30)),
            ],
        ),
    ]
