# Generated by Django 5.0.1 on 2024-02-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstForm', '0002_remove_student_id_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
